plugin:
    has_options: false
    icon: icap_eval_icon.png

    resources:
        - name: innova_collecticiel
          class: Innova\CollecticielBundle\Entity\Dropzone
          is_visible: true
          is_browsable: false
          icon: icap_eval_icon.png
          actions:
            - name: open
              menu_name: open_dropzone
            - name: edit
              menu_name: edit_dropzone
          activity_rules:
            - action: resource-innova_collecticiel-drop_evaluate
            - action: resource-innova_collecticiel-dropzone_manual_state_changed
