services:
    innova.listener.dropzone_listener:
        class: Innova\CollecticielBundle\Listener\DropzoneListener
        calls:
          - [setContainer, ["@service_container"]]
        tags:
          - { name: kernel.event_listener, event: create_form_innova_collecticiel, method: onCreateForm }
          - { name: kernel.event_listener, event: create_innova_dropzone, method: onCreate }
          - { name: kernel.event_listener, event: delete_innova_dropzone, method: onDelete }
          #- { name: kernel.event_listener, event: export_innova_dropzone, method: onExport }
          - { name: kernel.event_listener, event: copy_innova_dropzone, method: onCopy }
          - { name: kernel.event_listener, event: open_innova_dropzone, method: onOpen }
          - { name: kernel.event_listener, event: create_log_list_item_innova_dropzone, method: onCreateLogListItem }
          - { name: kernel.event_listener, event: create_log_details_innova_dropzone, method: onCreateLogDetails }
          - { name: kernel.event_listener, event: plugin_options_innovadropzone, method: onAdministrate }
          - { name: kernel.event_listener, event: edit_dropzone_innova_dropzone, method: onEdit }
          - { name: kernel.event_listener, event: list_dropzone_innova_dropzone, method: onList }
          - { name: kernel.event_listener, event: open_dropzone_innova_dropzone, method: onOpenCustom }

    innova.listener.document_listener:
        class: Innova\CollecticielBundle\Listener\DeleteListener
        calls:
          - [setContainer, ["@service_container"]]
        tags:
          - { name: doctrine.event_listener, event: preRemove }

    innova.listener.dropzone.display_log_listener:
            class: Innova\CollecticielBundle\Listener\Log\DisplayLogListener
            calls:
                - [setContainer, ["@service_container"]]
            tags:
                - { name: kernel.event_listener, event: create_log_details_resource-innova_dropzone-dropzone_configure,              method: onCreateLogDetails }
                - { name: kernel.event_listener, event: create_log_details_resource-innova_dropzone-criterion_create,                method: onCreateLogDetails }
                - { name: kernel.event_listener, event: create_log_details_resource-innova_dropzone-criterion_update,                method: onCreateLogDetails }
                - { name: kernel.event_listener, event: create_log_details_resource-innova_dropzone-criterion_delete,                method: onCreateLogDetails }
                - { name: kernel.event_listener, event: create_log_details_resource-innova_dropzone-drop_start,                      method: onCreateLogDetails }
                - { name: kernel.event_listener, event: create_log_details_resource-innova_dropzone-drop_end,                        method: onCreateLogDetails }
                - { name: kernel.event_listener, event: create_log_details_resource-innova_dropzone-document_create,                 method: onCreateLogDetails }
                - { name: kernel.event_listener, event: create_log_details_resource-innova_dropzone-document_delete,                 method: onCreateLogDetails }
                - { name: kernel.event_listener, event: create_log_details_resource-innova_dropzone-document_open,                   method: onCreateLogDetails }
                - { name: kernel.event_listener, event: create_log_details_resource-innova_dropzone-correction_start,                method: onCreateLogDetails }
                - { name: kernel.event_listener, event: create_log_details_resource-innova_dropzone-correction_end,                  method: onCreateLogDetails }
                - { name: kernel.event_listener, event: create_log_details_resource-innova_dropzone-correction_update,               method: onCreateLogDetails }
                - { name: kernel.event_listener, event: create_log_details_resource-innova_dropzone-correction_delete,               method: onCreateLogDetails }
                - { name: kernel.event_listener, event: create_log_details_resource-innova_dropzone-correction_validation_change,    method: onCreateLogDetails }
                - { name: kernel.event_listener, event: create_log_details_resource-innova_dropzone-drop_evaluate,                   method: onCreateLogDetails }
                - { name: kernel.event_listener, event: create_log_details_resource-innova_dropzone-drop_report,                     method: onCreateLogDetails }
                - { name: kernel.event_listener, event: create_log_details_resource-innova_dropzone-correction_report,               method: onCreateLogDetails }
                - { name: kernel.event_listener, event: create_log_details_resource-innova_dropzone-drop_grade_available,            method: onCreateLogDetails }
                - { name: kernel.event_listener, event: create_log_details_resource-innova_dropzone-dropzone_manual_state_changed,   method: onCreateLogDetails }

    innova.listener.dropzone.notification_listener:
            class: Innova\CollecticielBundle\Listener\NotificationListener
            calls:
                - [setContainer, ["@service_container"]]
            tags:
                - { name: kernel.event_listener, event: create_notification_item_resource-innova_dropzone-drop_report,                      method: onCreateNotificationItem }
                - { name: kernel.event_listener, event: create_notification_item_resource-innova_dropzone-correction_report,                method: onCreateNotificationItem }
                - { name: kernel.event_listener, event: create_notification_item_resource-innova_dropzone-drop_grade_available,             method: onCreateNotificationItem }
                - { name: kernel.event_listener, event: create_notification_item_resource-innova_dropzone-dropzone_manual_state_changed,    method: onCreateNotificationItem }
                - { name: kernel.event_listener, event: create_notification_item_resource-innova_dropzone-drop_end,                         method: onCreateNotificationItem }
